---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage-class.yaml
  - cr-sharded.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: mongodb-dbaas-platform
      app.kubernetes.io/managed-by: kustomize
