---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cm-mongodb-connections.yaml
  - cm-mongodb-replication.yaml
  - cm-mongodb-tenant-overview.yaml
  - cm-mongodb-wiredtiger.yaml
